version: "3"

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt
    restart: always
    env_file: .env
    networks:
      - flat-network

  nginx:
    image: nginx:1.17
    container_name: nginx
    env_file: .env
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - "${LOG_PATH}:/var/log/nginx"
    depends_on:
      - nuxt
    networks:
      - flat-network

networks:
  flat-network:
